### ISSUE TITLE
Broccoli Builder ran into an error with `SourceMapConcat` plugin

### ISSUE THREAD

**Issue by joshkg** [ef4/ember-auto-import#103]
I'm getting this error during build:
```
- build failed
Error: Build Canceled: Broccoli Builder ran into an error with `SourceMapConcat` plugin. 💥
ENOENT: no such file or directory, open 'super-cool-app/tmp/source_map_concat-input_base_path-BRHeoDdl.tmp/assets/test-support.js'
Error: ENOENT: no such file or directory, open 'super-cool-app/tmp/source_map_concat-input_base_path-BRHeoDdl.tmp/assets/test-support.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMap.addFile (super-cool-app/node_modules/fast-sourcemap-concat/lib/source-map.js:77:33)
    at headerFiles.forEach.file (super-cool-app/node_modules/broccoli-concat/concat.js:196:18)
    at Array.forEach (<anonymous>:null:null)
    at Concat.concat.end.concat (super-cool-app/node_modules/broccoli-concat/concat.js:194:26)
    at super-cool-app/node_modules/fast-sourcemap-concat/lib/source-map.js:431:14
    at new Promise (<anonymous>:null:null)
    at SourceMap.end (super-cool-app/node_modules/fast-sourcemap-concat/lib/source-map.js:418:12)
    at Concat._doLegacyBuild (super-cool-app/node_modules/broccoli-concat/concat.js:179:24)
    at Concat.build (super-cool-app/node_modules/broccoli-concat/concat.js:102:19)
    at super-cool-app/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (super-cool-app/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (super-cool-app/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (super-cool-app/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (super-cool-app/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Pipeline aborted
```
Using Ember 3.2 with ember-auto-import at 1.2.9 - I'm not sure what details are helpful, let me know and I will provide!

**Comment by DegreeDev** [comment]
I can add that this is only happening for me with my production build

**Comment by ef4** [comment]
Ugh, yes. I reintroduced #91. This is all fallout from trying to refactor to get around the new ember-cli internals making my life harder. 😛

**Comment by boris-petrov** [comment]
@ef4 - are you talking with the Ember-CLI guys about this? I'm pretty sure they will be listening to your feedback. :)

**Comment by joshkg** [comment]
Working like a charm now, thanks!

**Comment by marcemira** [comment]
I'm still getting the issue on latest `1.2.10`, using with `ember-cli": "~2.16.2"` and fastboot `"^1.1.4-beta.1"`. The package I'm trying to load is https://www.npmjs.com/package/typeit as `import TypeIt from 'typeit';`. Am I doing something wrong?

```
Build Error (SourceMapConcat)

ENOENT: no such file or directory, open '/Users/marcemira/projects/company/project/tmp/source_map_concat-input_base_path-cc23rea2.tmp/assets/vendor.js'


Stack Trace and Error Report: /var/folders/8k/79qd186d1fb1pkmh5wg6c43c0000gp/T/error.dump.d0ff2f277df689407cbb23e0193a603e.log
```
Cheers!
