### ISSUE TITLE
v1.2.11 Analyzer causing build error

### ISSUE THREAD

**Issue by nightire** [ef4/ember-auto-import#109]
Getting this error after upgrade to v1.2.11 from v1.2.10, when file changes:

```
file changed index/template.hbs
Build Error (Analyzer)

EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
```

here is the full log:

```
ENV Summary:

  TIME: Tue Aug 21 2018 17:17:08 GMT+0800 (China Standard Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/nightire/Code/choice-form/os-official/node_modules/.bin/ember
  - serve
  - --ssl
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/9_/y4f4n_cd5ddbzftt3x0rz19w0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin
  - /Users/nightire/Code/choice-form/os-official/node_modules/.bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/opt/texinfo/bin
  - /usr/local/opt/sqlite/bin
  - /usr/local/opt/openssl/bin
  - /usr/local/opt/libxml2/bin
  - /usr/local/opt/gettext/bin
  - /usr/local/opt/curl/bin
  - /Users/nightire/.cargo/bin
  - /usr/local/opt/gnu-tar/libexec/gnubin
  - /usr/local/Cellar/zplug/2.4.2/bin
  - /usr/local/sbin
  PLATFORM: darwin x64
  FREEMEM: 678449152
  TOTALMEM: 17179869184
  UPTIME: 677829
  LOADAVG: 1.8515625,2.23876953125,2.1943359375
  CPUS:
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz - 4000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.8.0
  - openssl: 1.1.0h
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.7.288.49-node.19
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
    at Object.symlinkSync (fs.js:869:3)
    at symlink (/Users/nightire/Code/choice-form/os-official/node_modules/symlink-or-copy/index.js:118:14)
    at Function.symlinkOrCopySync [as sync] (/Users/nightire/Code/choice-form/os-official/node_modules/symlink-or-copy/index.js:85:5)
    at getPatchset.forEach (/Users/nightire/Code/choice-form/os-official/node_modules/ember-auto-import/ts/analyzer.ts:95:25)
    at Array.forEach (<anonymous>)
    at Analyzer.build (/Users/nightire/Code/choice-form/os-official/node_modules/ember-auto-import/ts/analyzer.ts:68:24)
    at /Users/nightire/Code/choice-form/os-official/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
    at invokeCallback (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
    at publish (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:181:7)
  - codeFrame: EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Analyzer` plugin. 💥
EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Analyzer` plugin. 💥
EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
  - name: Error
  - nodeAnnotation: ember-auto-import-analyzer
  - nodeName: Analyzer
  - originalErrorMessage: EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
  - stack: Error: EEXIST: file already exists, symlink '/Users/nightire/Code/choice-form/os-official/tmp/broccoli_persistent_filtertemplate_compiler-output_path-U5ie8xKK.tmp/os-official/index/template.js' -> '/Users/nightire/Code/choice-form/os-official/tmp/analyzer-output_path-oU0fnTzU.tmp/os-official/index/template.js'
    at Object.symlinkSync (fs.js:869:3)
    at symlink (/Users/nightire/Code/choice-form/os-official/node_modules/symlink-or-copy/index.js:118:14)
    at Function.symlinkOrCopySync [as sync] (/Users/nightire/Code/choice-form/os-official/node_modules/symlink-or-copy/index.js:85:5)
    at getPatchset.forEach (/Users/nightire/Code/choice-form/os-official/node_modules/ember-auto-import/ts/analyzer.ts:95:25)
    at Array.forEach (<anonymous>)
    at Analyzer.build (/Users/nightire/Code/choice-form/os-official/node_modules/ember-auto-import/ts/analyzer.ts:68:24)
    at /Users/nightire/Code/choice-form/os-official/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
    at invokeCallback (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
    at publish (/Users/nightire/Code/choice-form/os-official/node_modules/promise-map-series/node_modules/rsvp/dist/lib/rsvp/-internal.js:181:7)
```

downgrade to v1.2.10 will solve this issue for now.

**Comment by urbany** [comment]
Also seeing this error after moving to v1.2.11
