### ISSUE TITLE
[v1.2.11] Ensure your input is sorted and has no duplicate paths

### ISSUE THREAD

**Issue by buschtoens** [ef4/ember-auto-import#110]
Downgrade to v1.2.10 fixes this. Possibly related to #109.

This is likely caused through ember-intl, which I am using in a lazily loaded engine, in case that is relevant.

I can whip up a reproduction, if you need one. :)

```
broccoliBuilderErrorStack: Error: expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
    at validateSortedUnique (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/util.js:13:13)
    at new FSTree (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/index.js:56:5)
    at Function.FSTree.fromEntries (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/index.js:79:10)
    at Append.upstreamPatchset (/Users/janbuschtoens/clark/application/node_modules/ember-auto-import/js/broccoli-append.js:100:72)
    at Append.build (/Users/janbuschtoens/clark/application/node_modules/ember-auto-import/js/broccoli-append.js:54:59)
    at /Users/janbuschtoens/clark/application/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:2415:5)
  - codeFrame: expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Append` plugin. 💥
expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Append` plugin. 💥
expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
  - name: Error
  - nodeAnnotation: ember-auto-import-analyzer
  - nodeName: Append
  - originalErrorMessage: expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
  - stack: Error: expected entries[7]: `assets/intl/intl.js` to be < entries[8]: `assets/intl/Intl.js.map`, but was not. Ensure your input is sorted and has no duplicate paths
    at validateSortedUnique (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/util.js:13:13)
    at new FSTree (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/index.js:56:5)
    at Function.FSTree.fromEntries (/Users/janbuschtoens/clark/application/node_modules/fs-tree-diff/lib/index.js:79:10)
    at Append.upstreamPatchset (/Users/janbuschtoens/clark/application/node_modules/ember-auto-import/js/broccoli-append.js:100:72)
    at Append.build (/Users/janbuschtoens/clark/application/node_modules/ember-auto-import/js/broccoli-append.js:54:59)
    at /Users/janbuschtoens/clark/application/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/janbuschtoens/clark/application/node_modules/rsvp/dist/rsvp.js:2415:5)
```

**Comment by miguelcobain** [comment]
I also experienced this exact same problem.

**Comment by scudmissile** [comment]
I'm also using ember-intl and I'm getting this same build error in all of our projects that use ember-intl.

**Comment by scudmissile** [comment]
Thanks, updating to 1.2.12 fixed my issue!
