### ISSUE TITLE
Broccoli Builder ran into an error with 'Analyzer' plugin

### ISSUE THREAD

**Issue by jbryson3** [ef4/ember-auto-import#13]
Just installed ember-auto-import after seeing the deprecation on ember-browserify.

Getting an error when I `ember serve`

```
Build Canceled: Broccoli Builder ran into an error with `Analyzer` plugin. 💥
Cannot read property 'elements' of undefined
TypeError: Cannot read property 'elements' of undefined
    at findAMDImports (/Users/jbryson3/code/arbiter/node_modules/ember-auto-import/lib/analyzer.js:98:5)
    at /Users/jbryson3/code/arbiter/node_modules/ember-auto-import/lib/analyzer.js:62:9
    at forEachNode (/Users/jbryson3/code/arbiter/node_modules/ember-auto-import/lib/analyzer.js:81:5)
    at forEachNode (/Users/jbryson3/code/arbiter/node_modules/ember-auto-import/lib/analyzer.js:84:7)
    at forEachNode (/Users/jbryson3/code/arbiter/node_modules/ember-auto-import/lib/analyzer.js:84:7)
```

It seems to alleviate the issue if I put a guard in analyzer.js

```js
function findAMDImports(entry, imports) {
  let e = head(entry.arguments.filter(function(item) {
    return item.type === 'ArrayExpression';
  }))
  if(!e){return}
//...
```
Here is the `entry.arguments` for the offending entry

```
[ Node {
    type: 'StringLiteral',
    start: 323,
    end: 334,
    loc: SourceLocation { start: [Object], end: [Object] },
    extra: { rawValue: 'clipboard', raw: '\'clipboard\'' },
    value: 'clipboard' },
  Node {
    type: 'FunctionExpression',
    start: 336,
    end: 375,
    loc: SourceLocation { start: [Object], end: [Object] },
    id: null,
    generator: false,
    async: false,
    params: [],
    body:
     Node {
       type: 'BlockStatement',
       start: 348,
       end: 375,
       loc: [Object],
       body: [Array],
       directives: [] } } ]
```

node: 8.11.2
ember-cli: 2.13.2

**Comment by ef4** [comment]
Thanks. Can you figure out which file it was trying to parse at the time? Running with `DEBUG=ember-auto-import:*` may give more info.

In any case, I hope to drop the AMD import analysis soon, by moving our analysis stage to a different part of the ember-cli build where it would always see only ES modules.

**Comment by jbryson3** [comment]
Ah, it did indeed. It was getting caught up on my `shims.js` file

```
define('clipboard', function() {
  return Clipboard;
});
```

I will re-adjust using the directions in README. thanks for the help!
