### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by michalo-iRonin** [ef4/ember-auto-import#148]
When I've tried install this addon I got this:
```resolver.ensureHook is not a function
Stack Trace and Error Report: /var/folders/3y/8vznb9jj5zd2nb3hzmqvnln40000gp/T/error.dump.bce8521aaeb36e4d5b8f6fa4ed12084f.log```

Do you support ember 2.18?
env: Ember 2.18

**Comment by ef4** [comment]
Yes, we support Ember 2.18.

Please share the contents of that error report file.

**Comment by michalo-iRonin** [comment]
```ENV Summary:

  TIME: Tue Nov 13 2018 10:57:09 GMT+0100 (CET)
  TITLE: ember
  ARGV:
  - /Users/michalolejniczak/.nvm/versions/node/v8.11.3/bin/node
  - /Users/michalolejniczak/.nvm/versions/node/v8.11.3/bin/ember
  - install
  - ember-auto-import
  EXEC_PATH: /Users/michalolejniczak/.nvm/versions/node/v8.11.3/bin/node
  TMPDIR: /var/folders/3y/8vznb9jj5zd2nb3hzmqvnln40000gp/T
  SHELL: /bin/zsh
  PATH:
  - /Users/michalolejniczak/.rvm/gems/ruby-2.5.0/bin
  - /Users/michalolejniczak/.rvm/gems/ruby-2.5.0@global/bin
  - /Users/michalolejniczak/.rvm/rubies/ruby-2.5.0/bin
  - /Users/michalolejniczak/.nvm/versions/node/v8.11.3/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/local/MacGPG2/bin
  - /Users/michalolejniczak
  - /Users/michalolejniczak/.rvm/bin
  PLATFORM: darwin x64
  FREEMEM: 561328128
  TOTALMEM: 17179869184
  UPTIME: 949623
  LOADAVG: 3.14599609375,2.78076171875,2.6650390625
  CPUS:
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  - Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz - 2200
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: resolver.ensureHook is not a function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: resolver.ensureHook is not a function
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: resolver.ensureHook is not a function
    at Object.exports.createResolver (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/enhanced-resolve/lib/ResolverFactory.js:154:11)
    at Object.<anonymous> (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/enhanced-resolve/lib/node.js:20:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-auto-import/js/splitter.js:17:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-auto-import/js/auto-import.js:6:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-auto-import/js/index.js:6:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.Addon.lookup (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/models/addon.js:1758:19)
    at graph.each (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/models/addons-factory.js:54:38)
    at Vertices.each (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/dag-map/dag-map.umd.js:197:13)
    at Vertices.walk (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/dag-map/dag-map.umd.js:125:14)
    at DAG.each (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/dag-map/dag-map.umd.js:68:24)
    at AddonsFactory.initializeAddons (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/models/addons-factory.js:45:11)
    at Project.initializeAddons (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/models/project.js:442:38)
    at Project.reloadAddons (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/models/project.js:584:17)
    at npmInstall.run.then (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/lib/tasks/addon-install.js:45:32)
    at tryCatcher (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/Users/michalolejniczak/Developer/Repositories/uplisting/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by ef4** [comment]
This is weird, the failure is happening while initializing a resolver from [enhanced-resolve](https://github.com/webpack/enhanced-resolve). We're not doing anything custom and it seems surprising that this would fail here.

What version of enhanced-resolve did you end up with?

You may have gotten messed up NPM packages, `rm -rf node_modules && npm install` may help.

**Comment by michalo-iRonin** [comment]
I have enhanced_resolve in version 0.9.1. Removing node_modules unfortunately doesn't help.

**Comment by mansona** [comment]
This looks like it's a very old issue so I'm closing it for now 👍 if anyone comes across this for Ember >= 3.28 let me know and I'll re-open the Issue
