### ISSUE TITLE
Import webpack-based dependency

### ISSUE THREAD

**Issue by allthesignals** [ef4/ember-auto-import#151]
I am attempting to import [this](https://github.com/Siqister/cddl-experiment-v2) package into my Ember project, but there are two moving pieces:

1. The webpack-based repository itself, which may be lacking some configuration
2. My configuration for `ember-auto-import`, which I may be doing incorrectly. 

I apologize for this not being a bug report, but I'm hoping to see some direction on how I might pinpoint this down. My lack of Webpack familiarity is making it hard for me to advise my colleague (who built the linked repo above) on what changes I need to import smoothly. 

Having this configuration seemed to get things to build:

```javascript
      alias: {
        'cddl-experiments-v2': '/src',
      },
```

but the run-time error complains about being unable to find it.

This seems completely wrong:
```javascript
      webpack: {
        entry: {
          'webpack-template': './src/index.js',
        },
      },
```

I have a feeling there is a `bundle.js` file that needs to be generated and committed to the dependency repository before I can move on. 

If anyone has any hints, they would be greatly appreciated - thank you!

**Comment by sukima** [comment]
Um `cddl-experiment-v2` [Does not exist](https://www.npmjs.com/search?q=cddl-experiment-v2). I'm not sure how `ember-auto-import` would be able to find this in your `node_modules`. Is this in a private NPM repository?

In either case when you install this module what are its output files. It has to build some kind of output file. You would tell `ember-auto-import` that the entry file is that. Then you *should* be able to `import GLModule from 'cddl-experiment-v2';` But my hunch is that the `cddl-experiment-v2` is not configured properly.

**Comment by allthesignals** [comment]
@sukima Thank you so much for the reply! `cddl-experiment-v2` is not published on npm - it's listed in my project like this: `"cddl-experiment-v2": "Siqister/cddl-experiment-v2",`. Yarn and npm allow you to install packages directly from Github. 

As for the output files, they are not committed to the repository I linked - it sounds like they should be. The build output in the repository is `dist/bundle.js`. I can definitely [get this committed](https://github.com/Siqister/cddl-experiment-v2/pull/3), I just wasn't sure it was the right approach. Once that happens, though, it sounds like I should try configuring `ember-auto-import` to point to that `dist/bundle.js` file?

Thanks again!

**Comment by allthesignals** [comment]
Hmm with the full bundle available in the package as `dist/bundle.js`, it seems to fail either at build time `ember s` or run time:

`Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'`

Here's the full log:

<details>

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
    at doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:180:19)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
  - codeFrame: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
  - errorMessage: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/mgardner/future-mobility-responses/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/bundler.js:24:9)
    at AutoImport.makeBundler (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:54:16)
    at AutoImport.addTo (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:63:38)
    at EmberApp.host.addonPostprocessTree (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:92:29)
    at EmberApp.toTree (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/broccoli/ember-app.js:1772:17)
    at module.exports (/Users/mgardner/future-mobility-responses/ember-cli-build.js:36:14)
    at Builder.readBuildFile (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/mgardner/future-mobility-responses/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/bundler.js:24:9)
    at AutoImport.makeBundler (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:54:16)
    at AutoImport.addTo (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:63:38)
    at EmberApp.host.addonPostprocessTree (/Users/mgardner/future-mobility-responses/node_modules/ember-auto-import/js/auto-import.js:92:29)
    at EmberApp.toTree (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/broccoli/ember-app.js:1772:17)
    at module.exports (/Users/mgardner/future-mobility-responses/ember-cli-build.js:36:14)
    at Builder.readBuildFile (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/mgardner/future-mobility-responses/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: Bundler
  - originalErrorMessage: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
  - stack: Error: Can't resolve 'cddl-experiment-v2' in '/Users/mgardner/future-mobility-responses'
    at doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:180:19)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/mgardner/future-mobility-responses/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/mgardner/future-mobility-responses/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
</details>
