### ISSUE TITLE
core_1.babelFilter is not a function

### ISSUE THREAD

**Issue by langalex** [ef4/ember-auto-import#239]
When building my Ember project which uses ember-auto-import I get this error:

```
Build Error (Bundler)

core_1.babelFilter is not a function


Stack Trace and Error Report: /var/folders/hk/zyky_0011f3_56_qxb6l6c440000gn/T/error.dump.c07418ba1d5e919b5a952cf868e96121.log
```

The log file looks like this:

```
=================================================================================

ENV Summary:

  TIME: Mon Aug 12 2019 14:00:38 GMT+0200 (Central European Summer Time)
  TITLE: ember
  ARGV:
  - /usr/local/Cellar/node/12.6.0/bin/node
  - /usr/local/bin/ember
  - test
  EXEC_PATH: /usr/local/Cellar/node/12.6.0/bin/node
  TMPDIR: /var/folders/hk/zyky_0011f3_56_qxb6l6c440000gn/T
  SHELL: /bin/bash
  PATH:
  - /usr/local/heroku/bin
  - /Users/langalex/bin
  - /usr/local/bin
  - /Users/langalex/.rbenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  PLATFORM: darwin x64
  FREEMEM: 2014900224
  TOTALMEM: 17179869184
  UPTIME: 1099105
  LOADAVG: 2.85986328125,2.26904296875,2.20751953125
  CPUS:
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  - Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz - 3300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 4
  - nghttp2: 1.38.0
  - node: 12.6.0
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.30.1
  - v8: 7.5.288.22-node.14
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: core_1.babelFilter is not a function
    at WebpackBundler.babelRule (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/webpack.js:123:38)
    at new WebpackBundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/webpack.js:112:30)
    at Bundler.get bundlerHook [as bundlerHook] (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:67:38)
    at Bundler.<anonymous> (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:78:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:10:58)
  - code: [undefined]
  - codeFrame: core_1.babelFilter is not a function
  - errorMessage: core_1.babelFilter is not a function
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/langalex/Projects/my-sample-project/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:31:9)
    at AutoImport.makeBundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:62:16)
    at AutoImport.addTo (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:72:38)
    at EmberApp.host.addonPostprocessTree (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:106:29)
    at EmberApp.toTree (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at module.exports (/Users/langalex/Projects/my-sample-project/ember-cli-build.js:108:20)
    at Builder.readBuildFile (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:31:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: core_1.babelFilter is not a function
        at Bundler
-~- created here: -~-
    at new Plugin (/Users/langalex/Projects/my-sample-project/node_modules/broccoli-plugin/index.js:7:31)
    at new Bundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:31:9)
    at AutoImport.makeBundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:62:16)
    at AutoImport.addTo (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:72:38)
    at EmberApp.host.addonPostprocessTree (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/auto-import.js:106:29)
    at EmberApp.toTree (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at module.exports (/Users/langalex/Projects/my-sample-project/ember-cli-build.js:108:20)
    at Builder.readBuildFile (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:51:14)
    at Builder.setupBroccoliBuilder (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:65:22)
    at new Builder (/Users/langalex/Projects/my-sample-project/node_modules/ember-cli/lib/models/builder.js:31:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: [undefined]
  - nodeName: Bundler
  - originalErrorMessage: core_1.babelFilter is not a function
  - stack: TypeError: core_1.babelFilter is not a function
    at WebpackBundler.babelRule (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/webpack.js:123:38)
    at new WebpackBundler (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/webpack.js:112:30)
    at Bundler.get bundlerHook [as bundlerHook] (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:67:38)
    at Bundler.<anonymous> (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:78:46)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/langalex/Projects/my-sample-project/node_modules/ember-auto-import/js/bundler.js:10:58)

=================================================================================

```

I'm not so sure what's going on here but the important part seems to be the `core_1.babelFilter is not a function`. `core_1` is coming from `import { babelFilter } from '@embroider/core';` ([code](https://github.com/ef4/ember-auto-import/blob/master/packages/ember-auto-import/ts/webpack.ts#L11)). My `@embroider/core` version is 0.4.3. My ember-auto-import is 1.5.2.

Any ideas anyone?

**Comment by langalex** [comment]
downgrading to 1.5.1 fixed it for now.
