### ISSUE TITLE
Incompatibility with ember-cli-fastboot

### ISSUE THREAD

**Issue by HenryVonfire** [ef4/ember-auto-import#247]
It seems that there's an incompatibility between `ember-auto-import` and `ember-cli-fastboot`. I'm importing `jspdf` package in a project using `ember-auto-import` and whenever I try to run `ember s` I get the following error. I've also checked that commenting out the import fixes the error.

Package versions:
ember-cli: 3.13.1
ember-source: 3.13.0
ember-auto-import: 1.5.2
ember-cli-fastboot: 2.2.1
jspdf: 1.5.3

```
TypeError: Cannot read property 'createElementNS' of undefined
    at eval (webpack://__ember_auto_import__/./node_modules/jspdf/dist/jspdf.min.js?:7363:17)
    at Object.eval (webpack://__ember_auto_import__/./node_modules/jspdf/dist/jspdf.min.js?:7427:4)
    at eval (webpack://__ember_auto_import__/./node_modules/jspdf/dist/jspdf.min.js?:4:37)
    at eval (webpack://__ember_auto_import__/./node_modules/jspdf/dist/jspdf.min.js?:7:2)
    at Object../node_modules/jspdf/dist/jspdf.min.js (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor.js:103143:1)
    at __webpack_require__ (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor.js:101387:30)
    at Module.eval [as callback] (webpack://__ember_auto_import__//tmp/broccoli-3138c48sGpzvzKaM/cache-328-bundler/staging/app.js?:15:40)
    at Module.exports (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:104:1)
    at requireModule (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/vendor/loader/loader.js:27:1)
    at Class._extractDefaultExport (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:432:1)
    at Class.resolveOther (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:103:1)
    at Class.resolve (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:163:1)
    at resolve (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:1200:1)
    at Registry.resolve (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:740:1)
    at Registry.resolve (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:743:1)
    at factoryFor (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:300:1)
    at instantiateFactory (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:353:1)
    at lookup (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:290:1)
    at Container.lookup (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:134:1)
    at Class.lookup (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:81:1)
    at Class.<anonymous> (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:1959:1)
    at untrack (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:3336:1)
    at untrack (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1253:1)
    at ComputedProperty.get (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:3335:1)
    at Class.CPGETTER_FUNCTION [as _qp] (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1044:1)
    at getPossibleMandatoryProxyValue (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1275:1)
    at get (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1348:1)
    at Class._getQPMeta (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/router.js:826:1)
    at Class._queryParamsFor (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/router.js:859:1)
    at forEachQueryParam (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/router.js:1500:1)
    at Class._deserializeQueryParams (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/router.js:690:1)
    at getFullQueryParams (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:1662:1)
    at getQueryParamsFor (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:1675:1)
    at Class.paramsFor (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:203:1)
    at Class._paramsFor (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:2319:1)
    at Class.deserialize (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/@ember/-internals/routing/lib/system/route.js:1041:1)
    at UnresolvedRouteInfoByParam.getModel (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/router_js.js:895:1)
    at _rsvp.Promise.resolve.then.then.then.then (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/router_js.js:691:1)
    at invokeCallback (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/rsvp.js:493:1)
    at publish (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/rsvp.js:476:1)
    at _runloop.backburner.schedule (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/ember-testing/lib/ext/rsvp.js:19:1)
    at invokeWithOnError (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/backburner.js:347:1)
    at Queue.flush (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/backburner.js:229:1)
    at DeferredActionQueues.flush (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/backburner.js:426:1)
    at Backburner._end (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/backburner.js:960:1)
    at Backburner._boundAutorunEnd (/tmp/broccoli-3138c48sGpzvzKaM/out-329-append_ember_auto_import_analyzer/assets/backburner.js:629:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ef4** [comment]
It looks like the jspdf code you're trying to import doesn't work in Node. They do appear to include a node-specific build in the published package, but there's nothing in package.json pointing at it, so we don't use it.

You can try aliasing `jspdf` to `jspdf/dist/jspdf.node.min.js`:

```
let app = new EmberApp(defaults, {
  autoImport: {
    alias: {
      'jspdf': 'jspdf/dist/jspdf.min.js',
    }
  }
});
```

But you'll need to do that only when building for fastboot, because in the browser you'll still want the browser build.

In general, fastboot depends on people writing code that's portable between browser and node. When it's not, there's manual interventions needed to work around those problems.

**Comment by HenryVonfire** [comment]
@ef4 thank you for taking time to look into this and for your explanation.
