### ISSUE TITLE
Tree Cycle Detected!

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#26]
All I did was install ember-auto-import (current sha: 19f75881cae56902b1a88eae9f13479d22f15a72)

got this error:
```
 cat /tmp/error.dump.deb618ea0c62404c1a6a52d196fd182a.log
=================================================================================

ENV Summary:

  TIME: Thu Jun 14 2018 13:12:00 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /home/me/.nvm/versions/node/v8.11.1/bin/node
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin/ember
  - serve
  EXEC_PATH: /home/me/.nvm/versions/node/v8.11.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.yarn/bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/.pythons/Python-3.6.3/bin
  - /home/me/.cargo/bin
  - /usr/local/heroku/bin
  - /home/me/node_modules/.bin
  - /home/me/apps/phantomjs/bin
  - /home/me/scripts/system-utils
  - /home/me/scripts/git
  - /home/me/scripts/rails
  - /home/me/scripts
  - /home/me/.nvm/versions/node/v8.11.1/bin
  - /home/me/.cargo/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/me/.fzf/bin
  - /home/me/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 132714496
  TOTALMEM: 8242163712
  UPTIME: 622957
  LOADAVG: 1.76806640625,1.61181640625,1.4375
  CPUS:
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 3244
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 3192
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 3257
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 3192
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.11.1
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Tree cycle detected
    at readAndReturnNodeFor (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:99:15)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:153:24
    at tryCatch (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  - codeFrame: Tree cycle detected
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Tree cycle detected
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Tree cycle detected
  - name: Error
  - nodeAnnotation: TreeMerger (preprocessedApp & templates)
  - nodeName: BroccoliMergeTrees
  - originalErrorMessage: Tree cycle detected
  - stack: Error: Tree cycle detected
    at readAndReturnNodeFor (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:99:15)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:153:24
    at tryCatch (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)


=================================================================================
```

I _did_ comment out my cjs transform for `instascan` (the library I was having issues loading before installing ember-auto-import:
```
  // app.import('node_modules/instascan/index.js', {
  //   using: [{ transformation: 'cjs', as: 'instascan' }]
  // });
```
the above 'works' sorta, but errors because it can't find the `fs` module.... not sure why it needs that. 

here is my pre-ember-auto-import ember-cli-build.js: https://github.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/ember-cli-build.js
(the only difference is that the instascan app.import isn't commented out)

**Comment by ef4** [comment]
This is an issue with ember-cli master. I bisected and 563bf268f5b564cd227ad034243064047f4bed07 changed the ordering the build pipeline in a way that defeats my clever hacks. Investigating further.

**Comment by NullVoxPopuli** [comment]
@ef4 latest attempt: different cause of error:
```
 $ cat /tmp/error.dump.5213d8368a1368bf1978a4e4e5f28143.log
=================================================================================

ENV Summary:

  TIME: Tue Jun 26 2018 16:58:23 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /home/me/.nvm/versions/node/v8.11.1/bin/node
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin/ember
  - serve
  - -p
  - 4201
  - -p
  - 4201
  EXEC_PATH: /home/me/.nvm/versions/node/v8.11.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/.config/yarn/link/node_modules/.bin
  - /home/me/.yarn/bin
  - /home/me/.nvm/versions/node/v8.11.1/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/lib/node_modules/npm/bin/node-gyp-bin
  - /home/me/.nvm/versions/node/v8.11.1/bin/node_modules/npm/bin/node-gyp-bin
  - /home/me/.pythons/Python-3.6.3/bin
  - /home/me/.cargo/bin
  - /usr/local/heroku/bin
  - /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/.bin
  - /home/me/apps/phantomjs/bin
  - /home/me/scripts/system-utils
  - /home/me/scripts/git
  - /home/me/scripts/rails
  - /home/me/scripts
  - /home/me/.nvm/versions/node/v8.11.1/bin
  - /home/me/.cargo/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/me/.fzf/bin
  - /home/me/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 139001856
  TOTALMEM: 8242159616
  UPTIME: 177245
  LOADAVG: 2.55029296875,2.11279296875,1.69091796875
  CPUS:
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2331
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2326
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2317
  - Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz - 2401
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.11.1
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.50
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Tree cycle detected
    at readAndReturnNodeFor (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:99:15)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:153:24
    at tryCatch (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  - codeFrame: Tree cycle detected
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Tree cycle detected
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `BroccoliMergeTrees` plugin. 💥
Tree cycle detected
  - name: Error
  - nodeAnnotation: TreeMerger (preprocessedApp & templates)
  - nodeName: BroccoliMergeTrees
  - originalErrorMessage: Tree cycle detected
  - stack: Error: Tree cycle detected
    at readAndReturnNodeFor (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:99:15)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/broccoli-builder/lib/builder.js:153:24
    at tryCatch (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:538:13)
    at /home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/home/me/Development/NullVoxPopuli/emberclear/packages/frontend/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by NullVoxPopuli** [comment]
oh, nevermind, that's the exact same. nvm. :(

**Comment by josemarluedke** [comment]
I was just testing out Ember CLI master and I had the same problem as @NullVoxPopuli.

**Comment by josemarluedke** [comment]
Just tested auto import again with the latest master (as of now) and still having errors. 

The error message seems different, so that might help debug this. 

I tested with the new Broccoli enabled (`EMBER_CLI_BROCCOLI_2=true EMBER_CLI_SYSTEM_TEMP=true ember serve`)

```Cycle in node graph: BroccoliMergeTrees (Full Application) -> BroccoliMergeTrees (TreeMerger (ExternalTree)) -> Funnel (Packaged Vendor) -> BroccoliMergeTrees (TreeMerger (vendor)) -> BundlerPlugin -> Analyzer (ember-auto-import-analyzer) -> Funnel () -> BroccoliMergeTrees (TreeMerger (preprocessedApp & templates)) -> BroccoliMergeTrees (Full Application)```

```
=================================================================================

ENV Summary:

  TIME: Mon Jul 30 2018 18:23:29 GMT-0700 (Pacific Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/josemarluedke/.nodenv/versions/10.7.0/bin/node
  - /Users/josemarluedke/.nodenv/versions/10.7.0/bin/ember
  - serve
  - -p
  - 4201
  EXEC_PATH: /Users/josemarluedke/.nodenv/versions/10.7.0/bin/node
  TMPDIR: /var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/josemarluedke/.nodenv/versions/10.7.0/bin
  - /usr/local/Cellar/nodenv/1.1.2/libexec
  - /Users/josemarluedke/.nodenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/josemarluedke/code/go/bin
  - /Users/josemarluedke/.fzf/bin
  PLATFORM: darwin x64
  FREEMEM: 322498560
  TOTALMEM: 17179869184
  UPTIME: 948797
  LOADAVG: 3.45849609375,3.19873046875,2.93994140625
  CPUS:
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.7.0
  - openssl: 1.1.0h
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.22.0
  - v8: 6.7.288.49-node.15
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cycle in node graph: BroccoliMergeTrees (Full Application) -> BroccoliMergeTrees (TreeMerger (ExternalTree)) -> Funnel (Packaged Vendor) -> BroccoliMergeTrees (TreeMerger (vendor)) -> BundlerPlugin -> Analyzer (ember-auto-import-analyzer) -> Funnel () -> BroccoliMergeTrees (TreeMerger (preprocessedApp & templates)) -> BroccoliMergeTrees (Full Application)
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cycle in node graph: BroccoliMergeTrees (Full Application) -> BroccoliMergeTrees (TreeMerger (ExternalTree)) -> Funnel (Packaged Vendor) -> BroccoliMergeTrees (TreeMerger (vendor)) -> BundlerPlugin -> Analyzer (ember-auto-import-analyzer) -> Funnel () -> BroccoliMergeTrees (TreeMerger (preprocessedApp & templates)) -> BroccoliMergeTrees (Full Application)
  - name: BuilderError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: BuilderError: Cycle in node graph: BroccoliMergeTrees (Full Application) -> BroccoliMergeTrees (TreeMerger (ExternalTree)) -> Funnel (Packaged Vendor) -> BroccoliMergeTrees (TreeMerger (vendor)) -> BundlerPlugin -> Analyzer (ember-auto-import-analyzer) -> Funnel () -> BroccoliMergeTrees (TreeMerger (preprocessedApp & templates)) -> BroccoliMergeTrees (Full Application)
    at Builder.makeNodeWrapper (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:216:15)
    at nodeInfo.inputNodes.map.inputNode (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:226:21)
    at Array.map (<anonymous>)
    at Builder.makeNodeWrapper (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:225:47)
    at nodeInfo.inputNodes.map.inputNode (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:226:21)
    at Array.map (<anonymous>)
    at Builder.makeNodeWrapper (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:225:47)
    at nodeInfo.inputNodes.map.inputNode (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:226:21)
    at Array.map (<anonymous>)
    at Builder.makeNodeWrapper (/Users/josemarluedke/code/tmp/test-cli/node_modules/broccoli/lib/builder.js:225:47)

=================================================================================```
