### ISSUE TITLE
Using Node.js modules in FastBoot

### ISSUE THREAD

**Issue by bobisjan** [ef4/ember-auto-import#266]
Hello,

I would like to move from FastBoot's custom import system to `ember-auto-import`, but I've discovered problem with packages using Node.js modules.

There is a minimal repository https://github.com/bobisjan/--ember-auto-import-fastboot.

Webpack throws `Module not found: Error: Can't resolve 'os' in '/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/system/src'`, I see other issues reported here, but they solve the problem by "mocking" native modules, but I expect that the code will run only in Node.js, using `node: false` or `node: { os: false }` does not work.

Should be the target `node` used for `dist/assets/auto-import-fastboot.js` by default to support FastBoot?

I tried using `target: 'node'` for experimentation and build finished successfully, but runtime error (in FastBoot) was thrown.

<details>
  <summary>ReferenceError: exports is not defined</summary>
  
  ```
/var/folders/4z/h7wb5mp50sxbqpt8bdt_nlg40000gn/T/broccoli-57263nrIkQrYu0Piz/out-272-append_ember_auto_import_analyzer/assets/auto-import-fastboot.js:1
exports.ids = [0];
^

ReferenceError: exports is not defined
    at /var/folders/4z/h7wb5mp50sxbqpt8bdt_nlg40000gn/T/broccoli-57263nrIkQrYu0Piz/out-272-append_ember_auto_import_analyzer/assets/auto-import-fastboot.js:1:1
    at Script.runInContext (vm.js:133:20)
    at VMSandbox.eval (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/ember-cli-fastboot/index.js:330:29)
    at Layer.handle [as handle_request] (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/express/lib/router/index.js:317:13)
    at /Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/bobisjan/Developer/ember-auto-import-fastboot/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
</details>

Thanks

**Comment by ef4** [comment]
>  would like to move from FastBoot's custom import system to ember-auto-import

I'm not really sure what this would mean. What's the benefit you're trying to get?

**Comment by bobisjan** [comment]
> What's the benefit you're trying to get?

1. Using standard JavaScript.

```javascript
// before
class Features extends Service {
  @service fastboot;

  async setup() {
    if (this.fastboot.isFastBoot) {
      const client = FastBoot.require('features-for-node');
      // ...
    } else {
      const client = await import('features-for-browser');
      // ...
    }
  }
}
```

```javascript
// after
class Features extends Service {
  @service fastboot;

  async setup() {
    if (this.fastboot.isFastBoot) {
      const client = await import('features-for-node');
      // ...
    } else {
      const client = await import('features-for-browser');
      // ...
    }
  }
}
```

2. No `npm install` of FastBoot dependencies on the server.

`fastboot-s3-downloader` [installs](https://github.com/ember-fastboot/fastboot-s3-downloader/blob/master/index.js#L43) FastBoot dependencies defined in `dist/package.json` with every deployment on the server. Using `ember-auto-import` makes this step a noop, because dependencies are bundled into `dist/assets/auto-import-fastboot.js` (if I understand this file correctly).

**Comment by ef4** [comment]
This is an interesting use case. We should be able to make it work, but it would need some attention.

One thing you could experiment with is using [webpack externals](https://webpack.js.org/configuration/externals/) to say explicitly that a package like `os` should be found via `FastBoot.require('os')` (and then presumably configure fastboot so that works, like I think you need to add `os` to the whitelist).

**Comment by bobisjan** [comment]
I've a have working [demo](https://github.com/bobisjan/--ember-auto-import-fastboot), using `externals` worked, thanks for the reference 👍.

Based on the documentation I've used `root` module context, see this [commit](https://github.com/bobisjan/--ember-auto-import-fastboot/commit/c7232de8e73045b274d444d151336d30ff4baa15).

I'm not sure if there is a way to register custom module context, eq. `fastboot`, which would use `FastBoot.require('...')` internally.

**Comment by ef4** [comment]
I think maybe it works if you do something like:

```
 autoImport: {
      webpack: {
        externals: {
          os: `FastBoot.require('os')`
        },
      },
    },
}
```

If not, there is also the ability to provide an arbitrary function that decide whether and how to externalize every import: https://webpack.js.org/configuration/externals/#function

**Comment by bobisjan** [comment]
@ef4 thanks, your example worked 👍, I misunderstood Webpack's documentation 🙈.

I've updated the demo by using list of [builtinsModules](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_module_builtinmodules) via function, so it is not required to explicitly provide every used builtin module in FastBoot.

```javascript
autoImport: {
  webpack: {
    externals: [
      function(context, request, callback) {
        if (builtinModules.includes(request)) {
          return callback(null, `FastBoot.require('${request}')`);
        }
        callback();
      }
    ],
  },
}
```

Does it make sense to provide this automatically via [configuration](https://github.com/ef4/ember-auto-import/blob/9f06682c643a85e3f2962d209a8cbb30cfe11396/packages/ember-auto-import/ts/webpack.ts#L90) when FastBoot is used?
