### ISSUE TITLE
Errors after upgrade to 1.0

### ISSUE THREAD

**Issue by Driezzz** [ef4/ember-auto-import#38]
I updated auto-iimport from 0.2.6 to 1.0.0 and i got the following error:

`ERROR in ./tmp/ember_auto_import_webpack-staging_dir-r6pCK2QC.tmp/entry.js
Module not found: Error: Can't resolve 'C:UsersadminDocumentsOculariumOculariumFrontend 2.0OculariumFrontendCore
ode_modulesocularium-sharedlibscenarioManager.js' `

Looks like the slashes are gone, the correct path should be like this:

`
C:Users/admin/Documents/Ocularium/OculariumFrontend 2.0/OculariumFrontendCore
ode_modules/ocularium-shared/lib/scenarioManager.js' 
`

> Hash: 56af320e769258f9084b
Version: webpack 4.12.1
Time: 72ms
Built at: 2018-06-25 09:57:04
 Asset      Size  Chunks             Chunk Names
app.js  4.52 KiB    main  [emitted]  main
Entrypoint main = app.js

Log file
```
=================================================================================

ENV Summary:

  TIME: Tue Jun 26 2018 11:51:16 GMT+0200 (Romance Daylight Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\admin\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - s
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\admin\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Program Files\Docker\Docker\Resources\bin;C
  - \Windows\system32;C
  - \Windows;C
  - \Windows\System32\Wbem;C
  - \Windows\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\Git\cmd;C
  - \Program Files\PuTTY\;C
  - \ProgramData\ComposerSetup\bin;C
  - \Program Files (x86)\Skype\Phone\;C
  - \Users\admin\AppData\Roaming\nvm;C
  - \Program Files\nodejs;C
  - \Program Files\nodejs\;C
  - \Users\admin\AppData\Local\Microsoft\WindowsApps;C
  - \PHP;C
  - \Users\admin\AppData\Roaming\Composer\vendor\bin;C
  - \Program Files\Microsoft VS Code\bin;C
  - \Users\admin\AppData\Roaming\nvm;C
  - \Users\admin\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 8131403776
  TOTALMEM: 17112006656
  UPTIME: 11703.1337309
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz - 3392
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at webpack.run (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\ember-auto-import\js\webpack.js:67:32)
    at finalCallback (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:157:39)
    at hooks.done.callAsync.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:206:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:204:22)
    at Compiler.emitRecords (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:319:39)
    at emitAssets.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:198:10)
    at hooks.afterEmit.callAsync.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:305:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `BundlerPlugin` plugin. 💥
webpack returned errors to ember-auto-import
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `BundlerPlugin` plugin. 💥
webpack returned errors to ember-auto-import
  - name: Error
  - nodeAnnotation: BundlerPlugin
  - nodeName: BundlerPlugin
  - originalErrorMessage: webpack returned errors to ember-auto-import
  - stack: Error: webpack returned errors to ember-auto-import
    at webpack.run (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\ember-auto-import\js\webpack.js:67:32)
    at finalCallback (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:157:39)
    at hooks.done.callAsync.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:206:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:204:22)
    at Compiler.emitRecords (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:319:39)
    at emitAssets.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:198:10)
    at hooks.afterEmit.callAsync.err (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\webpack\lib\Compiler.js:305:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\admin\Documents\Ocularium\OculariumFrontend 2.0\OculariumFrontendCore\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)

=================================================================================
```

**Comment by ef4** [comment]
Thanks for reporting. I don't have enough detail here to dig in further. 

The error message appears to be mangled -- maybe when you pasted it into GitHub the forward slashes in the path were interpreted as escapes?

Does the file it's complaining about exactly exist on your disk?

**Comment by Alexander-Krause** [comment]
Hi, the problem might occur on Windows machines only. My Ubuntu 18.04 is working fine, but on my colleague's Windows 10 the build fails.

This is the error message:
![capture](https://user-images.githubusercontent.com/9912468/41855221-5e34cdd2-7892-11e8-921a-f23727a11104.PNG)


This is the error dump content:

```
=================================================================================

ENV Summary:

  TIME: Mon Jun 25 2018 16:06:37 GMT+0200 (Central European Summer Time)
  TITLE: ember
  ARGV:
  - C:\Program Files\nodejs\node.exe
  - C:\Users\Christian\AppData\Roaming\npm\node_modules\ember-cli\bin\ember
  - build
  EXEC_PATH: C:\Program Files\nodejs\node.exe
  TMPDIR: C:\Users\CHRIST~1\AppData\Local\Temp
  SHELL: null
  PATH:
  - C
  - \Program Files\Docker\Docker\Resources\bin;C
  - \Program Files (x86)\Common Files\Oracle\Java\javapath;C
  - \ProgramData\Oracle\Java\javapath;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \Program Files\PuTTY\;C
  - \Program Files\Git\cmd;C
  - \Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
  - \Program Files (x86)\Gpg4win\..\GnuPG\bin;C
  - \Program Files\TortoiseGit\bin;C
  - \Program Files\TortoiseSVN\bin;C
  - \WINDOWS\system32;C
  - \WINDOWS;C
  - \WINDOWS\System32\Wbem;C
  - \WINDOWS\System32\WindowsPowerShell\v1.0\;C
  - \WINDOWS\System32\OpenSSH\;C
  - \Program Files\nodejs\;C
  - \Users\Christian\AppData\Local\Microsoft\WindowsApps;C
  - \texlive\2017\bin\win32;;C
  - \Users\Christian\AppData\Local\hyper\app-2.0.0\resources\bin;C
  - \Users\Christian\AppData\Roaming\npm
  PLATFORM: win32 x64
  FREEMEM: 1762775040
  TOTALMEM: 17059606528
  UPTIME: 10900
  LOADAVG: 0,0,0
  CPUS:
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  - Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz - 2592
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.14.0
  - cldr: 33.0
  - http_parser: 2.8.0
  - icu: 61.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.32.0
  - node: 10.5.0
  - openssl: 1.1.0h
  - tz: 2018c
  - unicode: 10.0
  - uv: 1.20.3
  - v8: 6.7.288.46-node.8
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at webpack.run (D:\tmp\explorviz-frontend\node_modules\ember-auto-import\js\webpack.js:67:32)
    at finalCallback (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:157:39)
    at hooks.done.callAsync.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:206:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\tmp\explorviz-frontend\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:204:22)
    at Compiler.emitRecords (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:319:39)
    at emitAssets.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:198:10)
    at hooks.afterEmit.callAsync.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:305:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\tmp\explorviz-frontend\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:302:27)
    at done (D:\tmp\explorviz-frontend\node_modules\neo-async\async.js:2854:11)
    at D:\tmp\explorviz-frontend\node_modules\neo-async\async.js:2805:7
    at D:\tmp\explorviz-frontend\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:97:16
    at D:\tmp\explorviz-frontend\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:42:10
    at D:\tmp\explorviz-frontend\node_modules\graceful-fs\graceful-fs.js:43:10
    at Object.apply (D:\tmp\explorviz-frontend\node_modules\harmony-reflect\reflect.js:2064:37)
    at FSReqWrap.oncomplete (fs.js:145:20)

  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `BundlerPlugin` plugin. 💥
webpack returned errors to ember-auto-import
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `BundlerPlugin` plugin. 💥
webpack returned errors to ember-auto-import
  - name: Error
  - nodeAnnotation: BundlerPlugin
  - nodeName: BundlerPlugin
  - originalErrorMessage: webpack returned errors to ember-auto-import
  - stack: Error: webpack returned errors to ember-auto-import
    at webpack.run (D:\tmp\explorviz-frontend\node_modules\ember-auto-import\js\webpack.js:67:32)
    at finalCallback (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:157:39)
    at hooks.done.callAsync.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:206:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\tmp\explorviz-frontend\node_modules\tapable\lib\Hook.js:35:21)
    at emitRecords.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:204:22)
    at Compiler.emitRecords (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:319:39)
    at emitAssets.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:198:10)
    at hooks.afterEmit.callAsync.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:305:14)
    at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\tmp\explorviz-frontend\node_modules\tapable\lib\Hook.js:35:21)
    at asyncLib.forEach.err (D:\tmp\explorviz-frontend\node_modules\webpack\lib\Compiler.js:302:27)
    at done (D:\tmp\explorviz-frontend\node_modules\neo-async\async.js:2854:11)
    at D:\tmp\explorviz-frontend\node_modules\neo-async\async.js:2805:7
    at D:\tmp\explorviz-frontend\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:97:16
    at D:\tmp\explorviz-frontend\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:42:10
    at D:\tmp\explorviz-frontend\node_modules\graceful-fs\graceful-fs.js:43:10
    at Object.apply (D:\tmp\explorviz-frontend\node_modules\harmony-reflect\reflect.js:2064:37)
    at FSReqWrap.oncomplete (fs.js:145:20)


=================================================================================
```

**Comment by Driezzz** [comment]
@ef4 I updated the log with full content, the error message at the start is exactly what was in the command window. It seems somehow all slashes were removed.
