### ISSUE TITLE
Getting Error: Cannot read property 'chrome' of undefined while updating ember-cli to 3.26.1

### ISSUE THREAD

**Issue by siva-sundar** [ef4/ember-auto-import#387]
Getting the following error while updating ember-cli and dependent addons from `3.8.1` to latest `3.26.1`

```javascript
Build Error (Analyzer)

[BABEL] unknown: Cannot read property 'chrome' of undefined (While processing: "/Users/falcon/node_modules/@babel/preset-env/lib/index.js")
```

Currently on:

```json

"ember-cli": "~3.26.1"
"ember-cli-babel": "^7.26.3",
"ember-auto-import": "^1.11.2"
```

Here is the complete trace.

```
- broccoliBuilderErrorStack: TypeError: [BABEL] unknown: Cannot read property 'chrome' of undefined (While processing: "/Users/falcon/node_modules/@babel/preset-env/lib/index.js")
    at getLowestImplementedVersion (/Users/falcon/node_modules/@babel/preset-env/node_modules/@babel/helper-compilation-targets/lib/utils.js:58:24)
    at /Users/falcon/node_modules/@babel/preset-env/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:26:77
    at Array.filter (<anonymous>)
    at targetsSupported (/Users/falcon/node_modules/@babel/preset-env/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:25:54)
    at isRequired (/Users/falcon/node_modules/@babel/preset-env/node_modules/@babel/helper-compilation-targets/lib/filter-items.js:58:11)
    at /Users/falcon/node_modules/@babel/preset-env/lib/index.js:300:201
    at /Users/falcon/node_modules/@babel/preset-env/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at sync (/Users/falcon/node_modules/@babel/core/lib/gensync-utils/async.js:27:25)
    at sync (/Users/falcon/node_modules/gensync/index.js:182:19)
    at /Users/falcon/node_modules/gensync/index.js:210:24
    at Generator.next (<anonymous>)
    at /Users/falcon/node_modules/@babel/core/lib/config/full.js:213:21
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/falcon/node_modules/@babel/core/lib/gensync-utils/async.js:16:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/falcon/node_modules/gensync/index.js:251:28)
  - code: [undefined]
  - codeFrame: [BABEL] unknown: Cannot read property 'chrome' of undefined (While processing: "/Users/falcon/node_modules/@babel/preset-env/lib/index.js")
  - errorMessage: [BABEL] unknown: Cannot read property 'chrome' of undefined (While processing: "/Users/falcon/node_modules/@babel/preset-env/lib/index.js")
        at Analyzer (ember-auto-import-analyzer)
-~- created here: -~-
    at new Plugin (/Users/falcon/node_modules/ember-qunit/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new Analyzer (/Users/falcon/node_modules/ember-qunit/node_modules/ember-auto-import/js/analyzer.js:72:9)
    at AutoImport.analyze (/Users/falcon/node_modules/ember-qunit/node_modules/ember-auto-import/js/auto-import.js:44:24)
    at Object.toTree (/Users/falcon/node_modules/ember-auto-import/js/index.js:31:59)
    at /Users/falcon/node_modules/ember-cli-preprocess-registry/preprocessors.js:188:26
    at Array.forEach (<anonymous>)
    at processPlugins (/Users/falcon/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:11)
    at Function.module.exports.preprocessJs (/Users/falcon/node_modules/ember-cli-preprocess-registry/preprocessors.js:179:10)
    at Class.preprocessJs (/Users/falcon/node_modules/ember-cli/lib/models/addon.js:1297:25)
    at Class.treeForAddonTestSupport (/Users/falcon/node_modules/ember-cli/lib/models/addon.js:945:19)
    at Class.treeForAddonTestSupport (/Users/falcon/node_modules/@coyote-labs/ember-accessibility/index.js:66:48)
    at Class.superWrapper [as treeForAddonTestSupport] (/Users/falcon/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/Users/falcon/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/Users/falcon/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /Users/falcon/node_modules/ember-cli/lib/broccoli/ember-app.js:697:26
    at Array.reduce (<anonymous>)

```

Any help would be greatly appreciated, thanks in advance!

**Comment by ef4** [comment]
What do you have in `config/targets.js`?

Does the problem go away if you remove node_modules and reinstall? (This is dumb but the unfortunate reality of npm and yarn having pretty bad bugs sometimes. In this case, it could be that `@babel/helper-compilation-targets` is getting an incorrect version of `browserslist`.)

**Comment by siva-sundar** [comment]
Thanks for the quick response!

This worked.
```sh
rm -rf node_modules && yarn cache clean && yarn
```

Closing the issue.
