### ISSUE TITLE
<my-addon> tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#425]
This is not desired (qunit should remain a dev dep).

But I can't find _where_ this is happening.

Is it possible to log which file the error is about?

<details><summary>Here is the full error</summary>

```

=================================================================================

ENV Summary:

  TIME: Tue Jul 20 2021 18:50:46 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/14.17.3/bin/node
  - /✂️/{my-monorepo}/shared/packages/{my-addon}/node_modules/.bin/ember
  - build
  EXEC_PATH: 🏠/.volta/tools/image/node/14.17.3/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - 🏠/.volta/tools/image/yarn/1.22.10/bin
  - 🏠/.volta/tools/image/node/14.17.3/bin
  - 🏠/.volta/bin
  - 🏠/.pyenv/plugins/pyenv-virtualenv/shims
  - 🏠/.pyenv/shims
  - 🏠/.pyenv/bin
  - /✂️/scripts/
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.volta/bin
  - 🏠/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - 🏠/.fzf/bin
  - /usr/lib/go-1.13/bin
  - /bin
  - 🏠/go/bin
  PLATFORM: linux x64
  FREEMEM: 2951323648
  TOTALMEM: 16790667264
  UPTIME: 64915.81
  LOADAVG: 2.54,1.8,1.54
  CPUS:
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 2.1.3
  - modules: 83
  - napi: 8
  - nghttp2: 1.42.0
  - node: 14.17.3
  - openssl: 1.1.1k
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.41.0
  - v8: 8.4.371.23-node.67
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
    at Package.assertAllowedDependency (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/package.js:205:19)
    at Package.resolve (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/package.js:195:14)
    at Splitter.<anonymous> (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:61:38)
    at Generator.next (<anonymous>)
    at /✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.handleLiteralImport (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:60:16)
    at Splitter.<anonymous> (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:50:32)
    at Generator.next (<anonymous>)
  - code: [undefined]
  - codeFrame: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
  - errorMessage: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/✂️/{my-monorepo}/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/webpack.js:106:9)
    at AutoImport.makeBundler (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/auto-import.js:95:16)
    at AutoImport.addTo (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/index.js:50:55)
    at /✂️/{my-monorepo}/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberAddon.toTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/✂️/{my-monorepo}/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/webpack.js:106:9)
    at AutoImport.makeBundler (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/auto-import.js:95:16)
    at AutoImport.addTo (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/index.js:50:55)
    at /✂️/{my-monorepo}/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberAddon.toTree (/✂️/{my-monorepo}/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: ember-auto-import-webpack
  - nodeName: WebpackBundler
  - originalErrorMessage: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
  - stack: Error: {my-addon} tried to import "qunit" from addon code, but "qunit" is a devDependency. You may need to move it into dependencies.
    at Package.assertAllowedDependency (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/package.js:205:19)
    at Package.resolve (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/package.js:195:14)
    at Splitter.<anonymous> (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:61:38)
    at Generator.next (<anonymous>)
    at /✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:4:12)
    at Splitter.handleLiteralImport (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:60:16)
    at Splitter.<anonymous> (/✂️/{my-monorepo}/node_modules/ember-auto-import/js/splitter.js:50:32)
    at Generator.next (<anonymous>)

=================================================================================

```

</details>

<details><summary>

`yarn list ember-auto-import`

</summary>

```
❯ yarn list ember-auto-import
yarn list v1.22.10

├─ @zestia/ember-dragula@10.0.9
│  └─ ember-auto-import@1.11.3
├─ ember-animated@0.10.1
│  └─ ember-auto-import@1.11.3
├─ ember-auto-import@2.0.2                <--- this is the one the addon (and every other workspace) specifies
├─ ember-changeset@3.13.9
│  └─ ember-auto-import@1.11.3
├─ ember-cli-deploy-cs@24.4.0
│  └─ ember-auto-import@1.11.3
├─ ember-exam@6.1.0
│  └─ ember-auto-import@1.11.3
├─ ember-focus-trap@0.7.0
│  └─ ember-auto-import@1.11.3
├─ ember-intl@5.7.0
│  └─ ember-auto-import@1.11.3
├─ ember-qunit@5.1.4
│  └─ ember-auto-import@1.11.3
├─ ember-statechart-component@2.3.6
│  └─ ember-auto-import@1.11.3
├─ ember-statecharts@0.13.2
│  └─ ember-auto-import@1.11.3
└─ ember-useragent@0.10.0
   └─ ember-auto-import@1.11.3
Done in 2.75s.
```

</details>

**Comment by NullVoxPopuli** [comment]
To debug: `DEBUG="ember-auto-import:*" ember build`

**Comment by NullVoxPopuli** [comment]
My addon had too much output for my terminal, so I output stderr and stdout to separate files:
```
AUTO_IMPORT_VERBOSE=true DEBUG="ember-auto-import:*" ember build 2> error.txt 1> output.txt
```

**Comment by NullVoxPopuli** [comment]
The above verbose logging did not provide _any_ insight as to which file is being problematic. 

So now I'll  run the build via 
```bash
JOBS=1 NODE_OPTIONS="--inspect-brk --trace-warnings --unhandled-rejections=strict" ember build
```
and open `chrome://inspect` in Chrome (I wish Firefox had a node debugger (but I guess it's a v8 vs Gecko thing))
and ensure that "Pause on exceptions" is blue/enabled.

**Comment by NullVoxPopuli** [comment]
Walking the stack back, I see that the problem file is:
```
"cs-core-api/test-support/assert-onerror.js"

**Comment by NullVoxPopuli** [comment]
looking at the stack, I see that problem file is: 
```
"<my-addon>/test-support/assert-onerror.js"
```
and on the file system, that's `addon-test-support/assert-onerror.js` 

Addon test support should be an ok place to import qunit, yeah?

**Comment by bendemboski** [comment]
@NullVoxPopuli if you only have `qunit` as a `devDependency`, then I don't think I'd expect this to work. `addon-test-support` is files that the addon supplies to consuming packages, i.e. it gets installed when your package is a dependency of another package, so all of its dependencies cannot just be `devDependencies`. You either need it to be a `dependency` or a `peerDependency` or something like that.

**Comment by bendemboski** [comment]
In other words, for this to work we'd have to teach `embroider` to make an exception and expect that `qunit` will _always_ be installed in packages that depend on addons, and even though that tends to be true practically speaking (if we pretend `ember-mocha` doesn't exist), it doesn't seem like something `embroider` should assume...

**Comment by NullVoxPopuli** [comment]
>  or a peerDependency o

:facepalm: ugh, that makes total sense. 

And that got my build to progress. yay!

**Comment by NullVoxPopuli** [comment]
And this should help protect future travelers: https://github.com/ef4/ember-auto-import/pull/435
