### ISSUE TITLE
Upgrade to 2.2.0 has caused module loading problems

### ISSUE THREAD

**Issue by NullVoxPopuli** [ef4/ember-auto-import#450]
I'm still investigating this, but wanted to start a thread in case others have the same issue.

Here is the CI run where I noticed this: https://github.com/NullVoxPopuli/ember-repl/pull/108/checks?check_run_id=3714822589#step:5:72
PR: https://github.com/NullVoxPopuli/ember-repl/pull/108

The errors reported in the build:
```
not ok 1 Chrome 93.0 - [3 ms] - TestLoader Failures: dummy/tests/rendering/compile-hbs-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            Error: Could not find module `babel-plugin-htmlbars-inline-precompile` imported from `ember-repl/cjs/index`
                at missingModule (http://localhost:7357/assets/vendor.js:259:11)
                at findModule (http://localhost:7357/assets/vendor.js:270:7)
                at Module.findDeps (http://localhost:7357/assets/vendor.js:180:24)
                at findModule (http://localhost:7357/assets/vendor.js:274:11)
                at Module.findDeps (http://localhost:7357/assets/vendor.js:180:24)
                at findModule (http://localhost:7357/assets/vendor.js:274:11)
                at Module.findDeps (http://localhost:7357/assets/vendor.js:180:24)
                at findModule (http://localhost:7357/assets/vendor.js:274:11)
                at requireModule (http://localhost:7357/assets/vendor.js:36:15)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:7681:9)
        message: >
            Died on test #1     at Object.test (webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?:407:34): Could not find module `babel-plugin-htmlbars-inline-precompile` imported from `ember-repl/cjs/index`
        negative: >
            false
        browser log: |
    ...
    
# ....    
    
not ok 3 Chrome 93.0 - [1 ms] - TestLoader Failures: dummy/tests/unit/utils-test: could not be loaded
    ---
        actual: >
            null
        stack: >
            TypeError: Cannot read properties of undefined (reading 'exports')
                at Module._reify (http://localhost:7357/assets/vendor.js:155:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:142:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:116:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:155:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:142:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:116:10)
                at requireModule (http://localhost:7357/assets/vendor.js:39:18)
                at TestLoader.require (http://localhost:7357/assets/test-support.js:7681:9)
                at TestLoader.loadModules (http://localhost:7357/assets/test-support.js:7673:14)
                at loadTests (http://localhost:7357/assets/test-support.js:8250:22)
        message: >
            Died on test #1     at Object.test (webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?:407:34): Cannot read properties of undefined (reading 'exports')
        negative: >
            false
        browser log: |
```

        
        
The first error seems to be different on different branches -- and it's always a module _that I most certainly_ have in `dependencies`

**Comment by NullVoxPopuli** [comment]
I had this happen on ember-auto-import 2.1 as well over here: https://github.com/NullVoxPopuli/ember-popperjs/pull/4
(before I upgraded to 2.2, since it seems whatever is causing this doesn't care about what version of ember-auto-import is in use)

**Comment by NullVoxPopuli** [comment]
ok, I think this is related to my webpack config 🤔

**Comment by NullVoxPopuli** [comment]
even if I reset all maybeEmbroider options and all index.js#options, I get an error about `babel-plugin-htmlbars-inline-precompile` not being able to be found 🤔

**Comment by NullVoxPopuli** [comment]
I figured it out. The very act of adding the template compiler.. breaks things. Not sure how yet. 

Here is the reproduction, split out by commit: https://github.com/NullVoxPopuli/reproduce-auto-import-450/commits/main

**Comment by NullVoxPopuli** [comment]
yeah, that's fair. I think my analysis was premature

**Comment by NullVoxPopuli** [comment]
So, I'm confused. Somehow this resolved itself in my ember-repl addon.
But I can't reproduce the resolution in the https://github.com/NullVoxPopuli/reproduce-auto-import-450/commits/main so.... I'm baffled. lol

**Comment by rwwagner90** [comment]
@NullVoxPopuli did you ever figure out what caused this error? I'm getting it in ember-light-table all the sudden

**Comment by NullVoxPopuli** [comment]
I did not. Likely some lock file issue?

Does light table use the template compiler?
Or any other legacy app.import stuff?
