### ISSUE TITLE
Error after manully deleting a file

### ISSUE THREAD

**Issue by leoplct** [ef4/ember-auto-import#47]
If i manually delete a file while my "ember server" is running i got this error.
If i stop server and re-run it again, it got solved.

Dang! Looks like a Build Error.
Cannot read property 'forEach' of null
Expand stack frames
Broccoli Plugin: BundlerPlugin
Build Canceled: Broccoli Builder ran into an error with `BundlerPlugin` plugin. ðŸ’¥ Cannot read property 'forEach' of null
                TypeError: Cannot read property 'forEach' of null
    at Object.keys.forEach.inPath (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:145:19)
    at Array.forEach (<anonymous>)
    at groupModules (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:144:22)
    at Analyzer.get imports [as imports] (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:39:23)
    at Splitter.depsForBundle (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/splitter.js:17:34)
    at BundlerPlugin.build (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/bundler.js:27:39)
    at /Users/leonardo/Dropbox/dev/dex/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:508:7)
              
                TypeError: Cannot read property 'forEach' of null
    at Object.keys.forEach.inPath (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:145:19)
    at Array.forEach (<anonymous>)
    at groupModules (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:144:22)
    at Analyzer.get imports [as imports] (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/analyzer.js:39:23)
    at Splitter.depsForBundle (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/splitter.js:17:34)
    at BundlerPlugin.build (/Users/leonardo/Dropbox/dev/dex/node_modules/ember-auto-import/lib/bundler.js:27:39)
    at /Users/leonardo/Dropbox/dev/dex/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/leonardo/Dropbox/dev/dex/node_modules/rsvp/dist/rsvp.js:508:7)

**Comment by ef4** [comment]
I think this is a dup of #36 fixed in 1.0.0.
