### ISSUE TITLE
Build fail after upgrading from 2.2.x to 2.3+

### ISSUE THREAD

**Issue by BnitoBzh** [ef4/ember-auto-import#501]
After upgrading ember-auto-import from 2.2.4 to 2.3.0 or 2.4.0 i get this error :
`Build Error (broccoli-persistent-filter:Babel > [Babel: @embroider/macros]) in @embroider/macros/runtime.js`

My ember application is in version 3.28.

I don't really know where to start debugging

The error summary : 
```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: @babel/template placeholder "614810638882094": Expected string substitution
    at applyReplacement (/Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:74:13)
    at /Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:44:7
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:42:43)
    at /Users/user/Projects/app/node_modules/@babel/template/lib/string.js:20:51
    at /Users/user/Projects/app/node_modules/@babel/template/lib/builder.js:75:14
    at Object.buildLiterals (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:73)
    at Object.inlineRuntimeConfig (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
    at PluginPass.enter (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
    at newFn (/Users/user/Projects/app/node_modules/@babel/traverse/lib/visitors.js:177:21)
    =============
    at Object.buildLiterals (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:34)
    at Object.inlineRuntimeConfig (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
    at PluginPass.enter (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
    at newFn (/Users/user/Projects/app/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/user/Projects/app/node_modules/@babel/traverse/lib/context.js:103:16)
  - code: [undefined]
  - codeFrame: /Users/user/Projects/app/@embroider/macros/runtime.js: @babel/template placeholder "614810638882094": Expected string substitution
  - errorMessage: @embroider/macros/runtime.js: /Users/user/Projects/app/@embroider/macros/runtime.js: @babel/template placeholder "614810638882094": Expected string substitution
        in /var/folders/2q/1cm88m51451gcjv0h86458hw0000gn/T/broccoli-53845dDDWr3UaHXgu/out-275-funnel_funnel_embroider_macros_addon
        at broccoli-persistent-filter:Babel > [Babel: @embroider/macros] (Babel: @embroider/macros)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @embroider/macros/runtime.js
    - line: [undefined]
    - treeDir: /var/folders/2q/1cm88m51451gcjv0h86458hw0000gn/T/broccoli-53845dDDWr3UaHXgu/out-275-funnel_funnel_embroider_macros_addon
  - message: @embroider/macros/runtime.js: /Users/user/Projects/app/@embroider/macros/runtime.js: @babel/template placeholder "614810638882094": Expected string substitution
        in /var/folders/2q/1cm88m51451gcjv0h86458hw0000gn/T/broccoli-53845dDDWr3UaHXgu/out-275-funnel_funnel_embroider_macros_addon
        at broccoli-persistent-filter:Babel > [Babel: @embroider/macros] (Babel: @embroider/macros)
  - name: Error
  - nodeAnnotation: Babel: @embroider/macros
  - nodeName: broccoli-persistent-filter:Babel > [Babel: @embroider/macros]
  - originalErrorMessage: /Users/user/Projects/app/@embroider/macros/runtime.js: @babel/template placeholder "614810638882094": Expected string substitution
  - stack: Error: @babel/template placeholder "614810638882094": Expected string substitution
    at applyReplacement (/Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:74:13)
    at /Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:44:7
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/Users/user/Projects/app/node_modules/@babel/template/lib/populate.js:42:43)
    at /Users/user/Projects/app/node_modules/@babel/template/lib/string.js:20:51
    at /Users/user/Projects/app/node_modules/@babel/template/lib/builder.js:75:14
    at Object.buildLiterals (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:73)
    at Object.inlineRuntimeConfig (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
    at PluginPass.enter (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
    at newFn (/Users/user/Projects/app/node_modules/@babel/traverse/lib/visitors.js:177:21)
    =============
    at Object.buildLiterals (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/evaluate-json.js:377:34)
    at Object.inlineRuntimeConfig (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/get-config.js:107:55)
    at PluginPass.enter (/Users/user/Projects/app/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js:77:38)
    at newFn (/Users/user/Projects/app/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/user/Projects/app/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/user/Projects/app/node_modules/@babel/traverse/lib/context.js:103:16)
```

**Comment by Windvis** [comment]
I think you are probably running into this `@embroider/macros` issue: https://github.com/embroider-build/embroider/issues/1077

If you run `npm ls @embroider/macros` or `yarn why @embroider/macros` you will probably see some versions older than 0.43. I would try checking if the addons that use that version have any new releases that bump the version, or PR that change.

You can work around the issue by using yarn resolutions or npm overrides (npm 8.3+) and forcing the version to v1.0.0, (it's possible that you need to force the version of some other `@embroider/*` packages as well).

**Comment by BnitoBzh** [comment]
Yes this is the issue ! 
ember-changeset use @embroider/macros@0.42.3

Fixed with yarn resolutions.

Thanks
