### ISSUE TITLE
Could not find module `path`

### ISSUE THREAD

**Issue by jking6884** [ef4/ember-auto-import#505]
I am using ember-auto-import ^2.2.4
It is loaded as a dependency in an addon that I maintian
I have `path-browserify` loaded as a dependency in the addon as well.

In the addon's `index.js` file, I have this configuration:

![image](https://user-images.githubusercontent.com/4825257/154766558-5ef55b25-f08c-459f-b74a-ec29cf026a59.png)

However, when I try to import Path with `import Path from 'path';`, I get this error:

![image](https://user-images.githubusercontent.com/4825257/154766788-0bda4e4e-a172-4c96-b6fb-ff0787d3e156.png)

**Comment by jking6884** [comment]
Any thoughts or insights in regards to this would be greatly appreciated.  I feel like, on the surface, this configuration should be working, but it's not :/

**Comment by jking6884** [comment]
This is the produced webpack config:

```{
  "mode": "development",
  "entry": {
    "app": [
      "/private/var/folders/l4/qv207kgj4c1df_1h0_dm71q00000gn/T/broccoli-57616QkGBmhbzvtdB/cache-738-webpack_bundler_ember_auto_import_webpack/l.js",
      "/private/var/folders/l4/qv207kgj4c1df_1h0_dm71q00000gn/T/broccoli-57616QkGBmhbzvtdB/cache-738-webpack_bundler_ember_auto_import_webpack/app.js"
    ],
    "tests": [
      "/private/var/folders/l4/qv207kgj4c1df_1h0_dm71q00000gn/T/broccoli-57616QkGBmhbzvtdB/cache-738-webpack_bundler_ember_auto_import_webpack/l.js",
      "/private/var/folders/l4/qv207kgj4c1df_1h0_dm71q00000gn/T/broccoli-57616QkGBmhbzvtdB/cache-738-webpack_bundler_ember_auto_import_webpack/tests.js"
    ]
  },
  "performance": {
    "hints": false
  },
  "target": "browserslist:last 1 Chrome versions,last 1 Firefox versions,last 1 Safari versions",
  "output": {
    "path": "/var/folders/l4/qv207kgj4c1df_1h0_dm71q00000gn/T/broccoli-57616QkGBmhbzvtdB/out-738-webpack_bundler_ember_auto_import_webpack/assets",
    "publicPath": "/assets/",
    "filename": "chunk.[id].[chunkhash].js",
    "chunkFilename": "chunk.[id].[chunkhash].js",
    "libraryTarget": "var",
    "library": "__ember_auto_import__"
  },
  "optimization": {
    "splitChunks": {
      "chunks": "all"
    }
  },
  "resolveLoader": {
    "alias": {
      "babel-loader-8": "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/babel-loader/lib/index.js",
      "eai-style-loader": "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/style-loader/dist/cjs.js",
      "eai-css-loader": "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/css-loader/dist/cjs.js"
    }
  },
  "resolve": {
    "extensions": [
      ".js",
      ".ts",
      ".json"
    ],
    "mainFields": [
      "browser",
      "module",
      "main"
    ],
    "alias": {},
    "fallback": {
      "path": "/Users/johnking/ws/meldcore-framework/node_modules/path-browserify/index.js",
      "process": "/Users/johnking/ws/meldcore-framework/node_modules/process/browser.js"
    }
  },
  "plugins": [
    {
      "definitions": {
        "Buffer": [
          "buffer",
          "Buffer"
        ]
      }
    }
  ],
  "module": {
    "rules": [
      {
        "use": {
          "loader": "babel-loader-8",
          "options": {
            "configFile": false,
            "babelrc": false,
            "generatorOpts": {
              "compact": true
            },
            "plugins": [
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/@babel/plugin-proposal-decorators/lib/index.js",
                {
                  "legacy": true
                }
              ],
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
                {
                  "loose": false
                }
              ],
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/babel-plugin-htmlbars-inline-precompile/index.js",
                {
                  "ensureModuleApiPolyfill": false,
                  "templateCompilerPath": "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-source/dist/ember-template-compiler.js",
                  "modules": {
                    "ember-cli-htmlbars": "hbs",
                    "@ember/template-compilation": {
                      "export": "precompileTemplate",
                      "disableTemplateLiteral": true,
                      "shouldParseScope": true,
                      "isProduction": false
                    }
                  }
                }
              ],
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/node_modules/@embroider/macros/src/babel/macros-babel-plugin.js",
                {
                  "userConfigs": {
                    "/Users/johnking/ws/meldcore-framework/node_modules/ember-get-config": {
                      "config": {
                        "modulePrefix": "heartzones-ui",
                        "podModulePrefix": "heartzones-ui/pods",
                        "environment": "development",
                        "rootURL": "/",
                        "locationType": "auto",
                        "EmberENV": {
                          "FEATURES": {},
                          "EXTEND_PROTOTYPES": {
                            "Date": false
                          },
                          "_APPLICATION_TEMPLATE_WRAPPER": false,
                          "_DEFAULT_ASYNC_OBSERVERS": true,
                          "_JQUERY_INTEGRATION": true,
                          "_TEMPLATE_ONLY_GLIMMER_COMPONENTS": true
                        },
                        "ifa": {
                          "enabled": true,
                          "inline": false
                        },
                        "ember-local-storage": {
                          "namespace": true,
                          "includeEmberDataSupport": false
                        },
                        "APP": {
                          "LOG_TRANSITIONS": false,
                          "restDestination": "http://localhost:4700",
                          "restNameSpace": "api",
                          "name": "heartzones-ui",
                          "version": "0.0.0+8365dfd9"
                        },
                        "auth": {
                          "login": "http://localhost:4700/api/auth/api-token-auth/",
                          "roles": "http://localhost:4700/api/user/roles",
                          "validateToken": "http://localhost:4700/api/auth/api-token-verify/",
                          "forgotPassword": "http://localhost:4700/api/forgot-password/",
                          "resetPassword": "http://localhost:4700/api/reset-password/"
                        },
                        "exportApplicationGlobal": true
                      }
                    },
                    "/Users/johnking/ws/meldcore-framework/node_modules/ember-bootstrap": {
                      "isBS3": false,
                      "isBS4": true,
                      "isBS5": false,
                      "isNotBS3": true,
                      "isNotBS5": true,
                      "version": "4.7.0"
                    }
                  },
                  "globalConfig": {
                    "@embroider/macros": {
                      "isTesting": false
                    }
                  },
                  "owningPackageRoot": null,
                  "isDevelopingPackageRoots": [
                    "/Users/johnking/ws/heartzones/heartzones-ui"
                  ],
                  "appPackageRoot": "/Users/johnking/ws/heartzones/heartzones-ui",
                  "embroiderMacrosConfigMarker": true,
                  "mode": "run-time",
                  "importSyncImplementation": "cjs"
                }
              ],
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
                {
                  "version": "a98a1070398bc8f170e528cbb3d3780bc794935e116284ef50628d61bc2bd78c"
                },
                "@embroider/macros cache buster: null"
              ]
            ],
            "presets": [
              [
                "/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/node_modules/@babel/preset-env/lib/index.js",
                {
                  "modules": false,
                  "targets": {
                    "browsers": [
                      "last 1 Chrome versions",
                      "last 1 Firefox versions",
                      "last 1 Safari versions"
                    ]
                  }
                }
              ]
            ]
          }
        }
      },
      {
        "test": {},
        "use": [
          {
            "loader": "eai-style-loader"
          },
          {
            "loader": "eai-css-loader"
          }
        ]
      }
    ]
  },
  "node": {
    "global": true,
    "__filename": true,
    "__dirname": true
  }
} ```

**Comment by jking6884** [comment]
@ef4 Does this seem like something that might be a bug?  I know @NullVoxPopuli is using some similar approaches, but in an Ember 4.x app using embroider for build pipeline.  I am in a 3.28.8 app and addon.

**Comment by ef4** [comment]
With ember-auto-import, webpack only handles the non-ember code. Your own ember code is analyzed to see what it imports, but not processed with webpack. So a fallback rule like this doesn't affect the ember code. It affects code down inside the libraries you're importing. 

The typical use case for path-browserify is to make a library that was originally written for node work in the browser. Using it from your own code is a bit unusual. But you can still do that if you want by either importing directly from "path-browserify" or by using ember-auto-import's alias option to alias it to "path", like you were trying to do with webpack's fallback.

**Comment by jking6884** [comment]
@ef4 That makes a lot of sense in regards to path.  I should probably just import that directly from `path-browserify`.

However, in the case of `@babel/generator` wanting to use `process`, I believe this more closely aligns to the standard use for `ember-auto-import`

<img width="537" alt="image" src="https://user-images.githubusercontent.com/4825257/154856241-43e16e5a-dece-4feb-9a14-b64aa9896900.png">

In the image above, I was able to use `DefinePlugin` and get it to work.  But I was not sure why I wasn't able to get `resolve.fallback.process` to work instead.

**Comment by jking6884** [comment]
I am able to resolve that with the DefinePlugin, but it would be interesting to know why the `process` fallback is not working.

However, this was the actual issue that I first encountered that led to me testing out different approaches and I am still getting this issue.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/4825257/154857901-3cfad2a2-3c3a-4dd5-9c8e-a00165da8053.png">

```
ERROR Summary:

  - broccoliBuilderErrorStack: Error: webpack returned errors to ember-auto-import
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/webpack.js:376:32
    at finalCallback (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:505:17
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.storeBuildDependencies (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Cache.js:122:37)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:906:5)
  - code: [undefined]
  - codeFrame: webpack returned errors to ember-auto-import
  - errorMessage: webpack returned errors to ember-auto-import
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/webpack.js:89:9)
    at AutoImport.makeBundler (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/auto-import.js:98:16)
    at AutoImport.addTo (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/index.js:49:55)
    at /Users/johnking/ws/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/johnking/ws/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/johnking/ws/ember-cli/lib/broccoli/ember-app.js:909:12)
    at EmberApp.toTree (/Users/johnking/ws/ember-cli/lib/broccoli/ember-app.js:1732:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
        - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: webpack returned errors to ember-auto-import
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/webpack.js:89:9)
    at AutoImport.makeBundler (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/auto-import.js:98:16)
    at AutoImport.addTo (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/index.js:49:55)
    at /Users/johnking/ws/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/johnking/ws/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/johnking/ws/ember-cli/lib/broccoli/ember-app.js:909:12)
    at EmberApp.toTree (/Users/johnking/ws/ember-cli/lib/broccoli/ember-app.js:1732:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: ember-auto-import-webpack
  - nodeName: WebpackBundler
  - originalErrorMessage: webpack returned errors to ember-auto-import
  - stack: Error: webpack returned errors to ember-auto-import
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/ember-auto-import/js/webpack.js:376:32
    at finalCallback (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:505:17
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.storeBuildDependencies (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Cache.js:122:37)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:501:19
    at Hook.eval [as callAsync] (eval at create (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at /Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/Users/johnking/ws/heartzones/heartzones-ui/node_modules/webpack/lib/Compiler.js:906:5)

=================================================================================
```

**Comment by jking6884** [comment]
I found the debug flags and used them when running the project and I saw this:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/4825257/154858284-f335f9a3-a558-4b2c-9fa9-7eb1dbed6b60.png">

I'm guessing this is probably the underlying reason.  Going to try stubbing `fs` with false.

**Comment by jking6884** [comment]
I added polyfills for several node packages that seemed to work for several of them.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/4825257/154859678-a36ae333-289a-40c0-a7f5-112e7d002a2a.png">

However, there were some other issues still coming up.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/4825257/154859701-89b89091-1d41-4aab-8324-b33f76e90b4d.png">

Is there a way to handle this with `ember-auto-import`?

**Comment by jking6884** [comment]
Does anyone have any thoughts on the additional information I provided in the comments above?

**Comment by ef4** [comment]
You're trying to use a library that uses Node's [module API](https://nodejs.org/dist/latest-v16.x/docs/api/module.html). That won't work in the browser unless you can polyfill it.

The best place to try to get help on this kind of problem is searching for issues that mention "webpack" and the library in question. If you're trying to use eslint in the browser via webpack, that's the terms you want to search for. 

It looks like it must be possible because [they have an in-browser demo](https://eslint.org/demo). But it may require you to do something less simple than just importing the eslint package. Maybe they have a browser-specific package, or browser-specific build inside their package, etc.
