### ISSUE TITLE
Build issue because of "Invalid configuration object"

### ISSUE THREAD

**Issue by mansona** [ef4/ember-auto-import#529]
I'm getting an error in an ember-try scenario that I'm trying to get passing: 

```
Build Error (WebpackBundler)

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features
```

<details>
  <summary>Here is the full output of the Error Report.</summary>
  
```
ENV Summary:

  TIME: Thu Jul 14 2022 15:06:32 GMT+0100 (Irish Standard Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/bin/ember
  - test
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/r5/bw5frvnn5k794hk62w3vp7km0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/mansona/.rvm/gems/ruby-2.6.3/bin
  - /Users/mansona/.rvm/gems/ruby-2.6.3@global/bin
  - /Users/mansona/.rvm/rubies/ruby-2.6.3/bin
  - /Users/mansona/Library/Android/sdk/platform-tools
  - /Users/mansona/Library/Android/sdk/tools
  - /Users/mansona/google-cloud-sdk/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/go/bin
  - /Library/Apple/usr/bin
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  - /Users/mansona/.cargo/bin
  - /Users/mansona/.rvm/bin
  - /Users/mansona/go/bin
  PLATFORM: darwin arm64
  FREEMEM: 213975040
  TOTALMEM: 34359738368
  UPTIME: 1126857
  LOADAVG: 15.9208984375,10.45654296875,11.802734375
  CPUS:
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  - Apple M1 Pro - 24
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 6.0.4
  - modules: 93
  - napi: 8
  - nghttp2: 1.45.1
  - nghttp3: 0.1.0-DEV
  - ngtcp2: 0.1.0-DEV
  - node: 16.13.0
  - openssl: 1.1.1l+quic
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 9.4.146.19-node.13
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
    at validate (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/webpack.js:158:32)
    at Object.f [as webpack] (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/index.js:64:16)
    at WebpackBundler.setup (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:189:43)
    at WebpackBundler.get stagingDir [as stagingDir] (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:106:21)
    at WebpackBundler.writeEntryFile (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:331:45)
    at WebpackBundler.<anonymous> (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:284:22)
    at Generator.next (<anonymous>)
  - code: [undefined]
  - codeFrame: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
  - errorMessage: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:89:9)
    at AutoImport.makeBundler (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/auto-import.js:98:16)
    at AutoImport.addTo (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/index.js:49:55)
    at /Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberAddon.toTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
        at WebpackBundler (ember-auto-import-webpack)
-~- created here: -~-
    at new Plugin (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new WebpackBundler (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:89:9)
    at AutoImport.makeBundler (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/auto-import.js:98:16)
    at AutoImport.addTo (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/auto-import.js:120:51)
    at Class.postprocessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/index.js:49:55)
    at /Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberAddon.addonPostprocessTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/broccoli/ember-app.js:843:12)
    at EmberAddon.toTree (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-cli/lib/broccoli/ember-app.js:1666:17)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: ember-auto-import-webpack
  - nodeName: WebpackBundler
  - originalErrorMessage: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
  - stack: ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node has an unknown property 'process'. These properties are valid:
   object { __dirname?, __filename?, global? }
   -> Options object for node compatibility features.
    at validate (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/webpack.js:111:24)
    at webpack (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/webpack.js:158:32)
    at Object.f [as webpack] (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/webpack/lib/index.js:64:16)
    at WebpackBundler.setup (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:189:43)
    at WebpackBundler.get stagingDir [as stagingDir] (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:106:21)
    at WebpackBundler.writeEntryFile (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:331:45)
    at WebpackBundler.<anonymous> (/Users/mansona/git/opensource/ember/guidemaker-ember-template/node_modules/ember-auto-import/js/webpack.js:284:22)
    at Generator.next (<anonymous>)
```
</details>

Any ideas on what I might be doing wrong? The current reproduction is the `fix-ci` branch of https://github.com/ember-learn/guidemaker-ember-template/tree/fix-ci and running the `ember-release` ember-try scenario: 

```
ember try:one ember-release --skip-cleanup
```

**Comment by mansona** [comment]
Thanks for this 🎉 I ended up finding the dependency that was using the process global and upgraded it so I just had to remove the config. Thanks for pointing me in the right direction 👍
