### ISSUE TITLE
uuid v9.0.0 import in fastboot fails with crypto.getRandomValues() not supported

### ISSUE THREAD

**Issue by hoIIer** [ef4/ember-auto-import#557]
I upgraded to latest [uuid](https://github.com/uuidjs/uuid) version v9.0.0 and my app won't run locally with fastboot, showing the stack trace below.

Trying to determine if this is an issue w/auto-import/webpack config or something with the uuid lib?

Any help appreciated!

Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
    at rng (webpack://__ember_auto_import__/./node_modules/uuid/dist/commonjs-browser/rng.js?:6:133)
    at v4 (webpack://__ember_auto_import__/./node_modules/uuid/dist/commonjs-browser/v4.js?:1:727)
    at Module.callback (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/ember-sqwok/mirage/config.js:13:1)
    at Module.exports (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:104:1)
    at requireModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:27:1)
    at r (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:176:1)
    at resolveInitializer (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/addon-tree-output/ember-load-initializers/index.js:9:1)
    at registerInitializers (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/addon-tree-output/ember-load-initializers/index.js:24:1)
    at loadInitializers (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/addon-tree-output/ember-load-initializers/index.js:59:1)
    at Module.callback (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/ember-sqwok/app.js:18:1)
    at Module.exports (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:104:1)
    at Object.requireModule (/var/folders/9r/gp7xyl_j0l3flcwp78j7mjcr0000gn/T/broccoli-84064el00SWqfsTbi/out-580-broccoli_merge_trees/assets/vendor/loader/loader.js:27:1)
    at Object.<anonymous> (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:169:18)
    at Sandbox.run (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/sandbox.js:66:15)
    at EmberApp.buildApp (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:168:30)
    at /Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:143:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EmberApp.getNewApplicationInstance (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:213:17)
    at EmberApp._visit (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:244:9)
    at EmberApp.visit (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/ember-app.js:329:7)
    at FastBoot.visit (/Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot/src/index.js:86:18)
    at /Users/eric/Projects/sqwok/ember-sqwok/node_modules/fastboot-express-middleware/src/index.js:33:20

**Comment by runspired** [comment]
fwiw uuid v4 is natively supported by both node and browser, you probably doing need that library
