### ISSUE TITLE
Broccoli Plugin: BundlerPlugin build error

### ISSUE THREAD

**Issue by jnkroeker** [ef4/ember-auto-import#65]
Hey there,

I'm attempting to pull a dependency in from an add-on. That dependency (leaflet.js) is also a dependency of the app consuming the add-on. I believe I have my ducks in a row with ember-auto-import as well as leaflet in dependencies and not devDependencies of the add-on. My add-on code is being imported from the /addon directory, but I have imported the leaflet dependency in /app as well:

`import Leaflet from 'leaflet';`
`export { default } from 'imi/components/map-config'; `

ember-auto-import is a devDependency in the consuming app while leaflet is a dependency. 

This code organization is working seamlessly with other addon/app combinations. Leaflet seems to be a problem. I am using leaflet version 1.3.1 which is an ES6 module. I am confused by the following build error: 

 Error: imi and imi-application are using different versions of leaflet (/imi/node_modules/leaflet/dist/leaflet-src.js vs /imi-application/node_modules/leaflet/dist/leaflet-src.js)
    at Splitter.<anonymous> (/imi-application/node_modules/ember-auto-import/js/splitter.js:77:31)
    at Generator.next (<anonymous>)
    at fulfilled (/imi-application/node_modules/ember-auto-import/js/splitter.js:4:58) 

Thanks in advance for clarification on this issue.

**Comment by ef4** [comment]
Ah, perhaps you are running with your addon `npm link`d into your app?

It looks like probably I missed that case when I wrote this version check. Right now it's being too strict -- it wants to make sure you're using exactly the same copy of leaflet from both places. If you're running npm linked, both will have their own copy.

Possible workaround: npm link leaflet into both the app and the addon.

**Comment by ef4** [comment]
Should be fixed in 1.2.3

**Comment by jnkroeker** [comment]
Brilliant! Solved that issue, but I have a follow on error I hope you might be able to shed light on:

Uncaught SyntaxError: Unexpected token :
    at Object../node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js (app.js:918)
    at __webpack_require__ (app.js:80)
    at Module.eval [as callback] (app.js:15)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:396)
    at Class.resolveOther (index.js:98)

**Comment by ef4** [comment]
Yeah, I can reproduce that, it's an instance of issue #58.
