### ISSUE TITLE
Build Error (Analyzer) Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by adibairpr** [ef4/ember-auto-import#76]
Getting this error occasionally

```
=================================================================================

ENV Summary:

  TIME: Thu Jul 26 2018 16:28:28 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /Users/penguin/.nvm/versions/node/v8.11.2/bin/node
  - /Users/penguin/git_repos/myproj/client/v3/node_modules/.bin/ember
  - serve
  - --proxy
  - http://localhost:4000
  - --port
  - 5200
  EXEC_PATH: /Users/penguin/.nvm/versions/node/v8.11.2/bin/node
  TMPDIR: /var/folders/ft/kgpw3hfn3xg3p7tg_5wtlz300000gn/T
  SHELL: /bin/zsh
  PLATFORM: darwin x64
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.29.0
  - node: 8.11.2
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _targets.Object.keys.map.fullPath (/Users/penguin/git_repos/myproj/client/v3/node_modules/ember-auto-import/lib/analyzer.js:34:84)
    at Array.map (<anonymous>)
    at Analyzer.build (/Users/penguin/git_repos/myproj/client/v3/node_modules/ember-auto-import/lib/analyzer.js:34:61)
    at /Users/penguin/git_repos/myproj/client/v3/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
  - codeFrame: Cannot convert undefined or null to object
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Analyzer` plugin. 💥
Cannot convert undefined or null to object
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `Analyzer` plugin. 💥
Cannot convert undefined or null to object
  - name: Error
  - nodeAnnotation: Analyzer
  - nodeName: Analyzer
  - originalErrorMessage: Cannot convert undefined or null to object
  - stack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at _targets.Object.keys.map.fullPath (/Users/penguin/git_repos/myproj/client/v3/node_modules/ember-auto-import/lib/analyzer.js:34:84)
    at Array.map (<anonymous>)
    at Analyzer.build (/Users/penguin/git_repos/myproj/client/v3/node_modules/ember-auto-import/lib/analyzer.js:34:61)
    at /Users/penguin/git_repos/myproj/client/v3/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/penguin/git_repos/myproj/client/v3/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

=================================================================================
```

**Comment by ef4** [comment]
This stack trace looks like its from an older version of ember-auto-import. Please try updating, and we can reopen if this is still happening. Thanks.
